Add Duplicate Vaccines & Recurring Service Record Checks
opensrp/opensrp-client-immunization pull request #195
Opened 2022-10-03 10:59 UTC by qiarie

- [x] Add duplicate vaccine checks
- [x] Add duplicate recurring service record checks
- [x] Migrate logging to Timber

2022-10-05 09:05 UTC, hilpitome reviewed
lgtm

2022-10-14 10:50 UTC, ekigamba requested changes

2022-10-14 10:50 UTC, ekigamba commented on opensrp-immunization/src/test/java/org/smartregister/immunization/repository/RecurringServiceRecordRepositoryTest.java
> +                        anyString(), any(String[].class), anyString(), any(String[].class),
Let's mock only the specific query and params here

2022-10-14 10:50 UTC, ekigamba commented on opensrp-immunization/src/test/java/org/smartregister/immunization/repository/RecurringServiceRecordRepositoryTest.java
> +                .query(anyString(), any(String[].class), anyString(), any(String[].class),
Let's verifiy the specific strings params here

2022-10-14 10:50 UTC, ekigamba commented on opensrp-immunization/src/test/java/org/smartregister/immunization/repository/RecurringServiceRecordRepositoryTest.java
> +                anyString(), any(String[].class), anyString(), any(String[].class),
Let's mock the specifc query and params here

2022-10-14 10:50 UTC, ekigamba commented on opensrp-immunization/src/test/java/org/smartregister/immunization/repository/RecurringServiceRecordRepositoryTest.java
> +        Mockito.verify(sqliteDatabase, Mockito.times(0))
Let's verify the specifc query and params here

2022-10-14 10:50 UTC, ekigamba commented on opensrp-immunization/src/test/java/org/smartregister/immunization/repository/RecurringServiceRecordRepositoryTest.java
> +        cursor.addRow(new Object[]{1L, "base-entity-id", "", 1L, "", magicNumber, "", "", "", "", "", "", "", "", 1L, magicDate});
We don't need this two lines since we are not returning the cursor

2022-12-09 10:04 UTC, ekigamba approved these changes

2022-12-09 10:06 UTC, merged